name: minha_ebd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

  # Banco de dados local
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

  sqflite: ^2.4.2
  signals: ^6.0.2
  path: ^1.9.1
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  mask_text_input_formatter: ^2.9.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generator do Hive CE
  hive_ce_generator: ^1.10.0
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icone.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/icone.png"
    background_color: "#035AA6"
    theme_color: "#035AA6"
  windows:
    generate: true
    image_path: "images/icone.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/icone.png"

flutter:
  uses-material-design: true

  assets:
    - imagens/icone.png
    - imagens/aulas.png
    - imagens/professores.png
    - imagens/superintendentes.png
    - imagens/classes.png
    - imagens/igreja.png
    - imagens/revistas.png
    - imagens/faixa_etaria.png
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
